spring.application.name=${AUTH_SERVICE_APPLICATION_NAME:auth-service}
spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/life_vault_db}
spring.datasource.driver-class-name=${DB_DRIVER:org.mariadb.jdbc.Driver}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:123456}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=${JPA_OPEN_IN_VIEW:false}
spring.sql.init.mode=${SQL_INIT_MODE:never}

auth.jwt.secret=${AUTH_JWT_SECRET:84656880a6cf588bc33d33fc69a0096a04ab7ef1a2678ff8f1b76e440e6a055f}
auth.jwt.access-token-ttl-seconds=${AUTH_ACCESS_TOKEN_TTL_SECONDS:900}
auth.jwt.reauth-token-ttl-seconds=${AUTH_REAUTH_TOKEN_TTL_SECONDS:300}
auth.refresh-token-ttl-seconds=${AUTH_REFRESH_TOKEN_TTL_SECONDS:2592000}
auth.max-failed-login-count=${AUTH_MAX_FAILED_LOGIN_COUNT:5}
auth.lock-duration-minutes=${AUTH_LOCK_DURATION_MINUTES:15}
auth.password.bcrypt-strength=${AUTH_BCRYPT_STRENGTH:10}
auth.redis.blacklist-enabled=${AUTH_REDIS_BLACKLIST_ENABLED:true}
auth.redis.failure-backoff-seconds=${AUTH_REDIS_FAILURE_BACKOFF_SECONDS:30}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=${REDIS_TIMEOUT:100ms}
spring.data.redis.connect-timeout=${REDIS_CONNECT_TIMEOUT:100ms}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
server.port=5001
