spring.application.name=${VAULT_SERVICE_APPLICATION_NAME:vault-service}
spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/life_vault_db?createDatabaseIfNotExist=true&useSsl=false&gssapiMechanisms=none}
spring.datasource.driver-class-name=${DB_DRIVER:org.mariadb.jdbc.Driver}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:123456}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=${JPA_OPEN_IN_VIEW:false}
spring.sql.init.mode=${SQL_INIT_MODE:never}
server.port=5002

vault.jwt.secret=${AUTH_JWT_SECRET:84656880a6cf588bc33d33fc69a0096a04ab7ef1a2678ff8f1b76e440e6a055f}
vault.encryption.secret=${VAULT_ENCRYPTION_SECRET:9e5d2a8b6d0f4f0a9f7f1e2d3c4b5a69788776655443322110abcdeffedcba98}
vault.storage.root=${VAULT_STORAGE_ROOT:./storage/vault-files}
vault.storage.max-file-size-bytes=${VAULT_MAX_FILE_SIZE_BYTES:10485760}
vault.storage.allowed-mime-types=${VAULT_ALLOWED_MIME_TYPES:image/jpeg,image/png,application/pdf,text/plain,application/octet-stream}

spring.servlet.multipart.max-file-size=${VAULT_MULTIPART_MAX_FILE_SIZE:10MB}
spring.servlet.multipart.max-request-size=${VAULT_MULTIPART_MAX_REQUEST_SIZE:12MB}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
