spring.application.name=${VAULT_SERVICE_APPLICATION_NAME:vault-service}
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/life_vault_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.open-in-view=${JPA_OPEN_IN_VIEW:false}
spring.sql.init.mode=${SQL_INIT_MODE:never}
